---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.nginx.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    matchLabels:
      run: "{{ .Values.nginx.name }}"
  replicas: {{ .Values.nginx.replicas }}
  template:
    metadata:
      labels:
        run: "{{ .Values.nginx.name }}"
    spec:
      containers:
        - name: "{{ .Values.nginx.name }}"
          image: "{{ .Values.nginx.image }}"
          ports:
            - containerPort: {{ .Values.nginx.port }}
          resources:
            limits:
              cpu: "{{ .Values.nginx.limits.cpu }}"
              memory: "{{ .Values.nginx.limits.ram }}"
            requests:
              cpu: "{{ .Values.nginx.requests.cpu }}"
              memory: "{{ .Values.nginx.requests.ram }}"
