---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Values.nginx.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.nginx.name }}"
  minReplicas: {{ .Values.nginx.hpa.min }}
  maxReplicas: {{ .Values.nginx.hpa.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.nginx.hpa.avgCpuUtil }}
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: "{{ .Values.nginx.hpa.avgRamVal }}"
