---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.nginx.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    run: "{{ .Values.nginx.name }}"
spec:
  ports:
    - port: {{ .Values.nginx.port }}
  selector:
    run: "{{ .Values.nginx.name }}"
