---
namespace: web-apps
nginx:
  name: nginx
  image: nginx:1.22.1-alpine
  port: 80
  limits:
    cpu: 1000m
    ram: 1000Mi
  requests:
    cpu: 200m
    ram: 500Mi
  hpa:
    min: 1
    max: 5
    avgCpuUtil: 50
    avgRamVal: 100Mi
